- added yast2_basis as requested in 1087944
yast/system-role-hpc-compute pull request #3
Opened 2018-04-04 09:09 UTC by mslacken

2018-04-04 09:20 UTC, imobachgs approved these changes

2018-04-04 19:44 UTC, imobachgs requested changes

2018-04-04 19:44 UTC, imobachgs commented on control/installation.xml
> +
The closing `</workflows>` element is missing.

2018-04-05 08:01 UTC, mslacken commented
As the workflow changes do not have the desired effect, I removed them all

2018-04-05 08:05 UTC, imobachgs approved these changes

2018-04-05 08:08 UTC, merged