updated patterns and partitions
yast/system-role-hpc-compute pull request #6
Opened 2018-04-20 14:09 UTC by mslacken

- changed required pattern from minimal_base to base (bsc#1090282) 
- added subvolume description to installation.xml to make btrfs
  available on guided partitioner (bsc#1090380)

2018-04-20 14:18 UTC, imobachgs approved these changes

2018-04-20 14:20 UTC, imobachgs requested changes

2018-04-20 14:20 UTC, imobachgs commented on control/installation.xml
> +			<snapshots config:type="boolean">true</snapshots>
Check indentantion, please.

2018-04-20 17:13 UTC, mslacken commented on control/installation.xml
> +			<snapshots config:type="boolean">true</snapshots>
are there rules for that?

2018-04-23 09:10 UTC, mslacken commented
updated intendation and comment

2018-04-23 09:27 UTC, mslacken commented
- updated intendation

2018-04-23 09:37 UTC, imobachgs requested changes
It looks much better know, although I've spotted a typo in a comment. Could you check it, please?

2018-04-23 09:37 UTC, imobachgs commented on control/installation.xml
> +                           max), because big simultion will go here -->
I guess *simultion* is a typo, right?

2018-04-23 10:08 UTC, imobachgs approved these changes

2018-04-23 10:08 UTC, merged